include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - build/**
    - example/build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
  errors:
    public_member_api_docs: error

linter:
  rules:
    - public_member_api_docs
    - comment_references
    - always_declare_return_types
    - avoid_dynamic_calls
    - avoid_unused_constructor_parameters
    - directives_ordering
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_final_locals
    - prefer_relative_imports
    - require_trailing_commas
    - sort_pub_dependencies
    - unawaited_futures
    - unnecessary_lambdas
    - unnecessary_parenthesis
    - use_super_parameters
